/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */
package kr.ac.snu.ids.PRJ1_1_2013_12295;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE = 9;
  /** RegularExpression Id. */
  int DROP = 10;
  /** RegularExpression Id. */
  int DESC = 11;
  /** RegularExpression Id. */
  int SHOW = 12;
  /** RegularExpression Id. */
  int SELECT = 13;
  /** RegularExpression Id. */
  int INSERT = 14;
  /** RegularExpression Id. */
  int DELETE = 15;
  /** RegularExpression Id. */
  int TABLE = 16;
  /** RegularExpression Id. */
  int TABLES = 17;
  /** RegularExpression Id. */
  int INTO = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int NULL = 20;
  /** RegularExpression Id. */
  int IS = 21;
  /** RegularExpression Id. */
  int AS = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int OR = 24;
  /** RegularExpression Id. */
  int FROM = 25;
  /** RegularExpression Id. */
  int WHERE = 26;
  /** RegularExpression Id. */
  int VALUES = 27;
  /** RegularExpression Id. */
  int PRIMARY = 28;
  /** RegularExpression Id. */
  int FOREIGN = 29;
  /** RegularExpression Id. */
  int KEY = 30;
  /** RegularExpression Id. */
  int REFERENCES = 31;
  /** RegularExpression Id. */
  int SEMICOLON = 32;
  /** RegularExpression Id. */
  int LEFT_PAREN = 33;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int PERIOD = 36;
  /** RegularExpression Id. */
  int UNDERSCORE = 37;
  /** RegularExpression Id. */
  int QUOTE = 38;
  /** RegularExpression Id. */
  int INT_VALUE = 39;
  /** RegularExpression Id. */
  int DATE_VALUE = 40;
  /** RegularExpression Id. */
  int NNNN = 41;
  /** RegularExpression Id. */
  int NN = 42;
  /** RegularExpression Id. */
  int SIGN = 43;
  /** RegularExpression Id. */
  int ASTERISK = 44;
  /** RegularExpression Id. */
  int COMP_OP = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 47;
  /** RegularExpression Id. */
  int ALPHABET = 48;
  /** RegularExpression Id. */
  int CHAR_STRING = 49;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTER = 50;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create\"",
    "\"drop\"",
    "\"desc\"",
    "\"show\"",
    "\"select\"",
    "\"insert\"",
    "\"delete\"",
    "\"table\"",
    "\"tables\"",
    "\"into\"",
    "\"not\"",
    "\"null\"",
    "\"is\"",
    "\"as\"",
    "\"and\"",
    "\"or\"",
    "\"from\"",
    "\"where\"",
    "\"values\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"references\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"_\"",
    "\"\\\'\"",
    "<INT_VALUE>",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
    "<SIGN>",
    "\"*\"",
    "<COMP_OP>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "<CHAR_STRING>",
    "<NON_QUOTE_SPECIAL_CHARACTER>",
    "<NON_QUOTE_CHARACTER>",
  };

}
