/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */
package kr.ac.snu.ids.PRJ1_1_2013_12295;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE = 9;
  /** RegularExpression Id. */
  int DROP = 10;
  /** RegularExpression Id. */
  int DESC = 11;
  /** RegularExpression Id. */
  int SHOW = 12;
  /** RegularExpression Id. */
  int TABLE = 13;
  /** RegularExpression Id. */
  int TABLES = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int NULL = 16;
  /** RegularExpression Id. */
  int PRIMARY = 17;
  /** RegularExpression Id. */
  int FOREIGN = 18;
  /** RegularExpression Id. */
  int KEY = 19;
  /** RegularExpression Id. */
  int REFERENCES = 20;
  /** RegularExpression Id. */
  int SEMICOLON = 21;
  /** RegularExpression Id. */
  int LEFT_PAREN = 22;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int UNDERSCORE = 25;
  /** RegularExpression Id. */
  int INT_VALUE = 26;
  /** RegularExpression Id. */
  int DATE_VALUE = 27;
  /** RegularExpression Id. */
  int NNNN = 28;
  /** RegularExpression Id. */
  int NN = 29;
  /** RegularExpression Id. */
  int SIGN = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 32;
  /** RegularExpression Id. */
  int ALPHABET = 33;
  /** RegularExpression Id. */
  int QUOTE = 34;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTER = 35;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create\"",
    "\"drop\"",
    "\"desc\"",
    "\"show\"",
    "\"table\"",
    "\"tables\"",
    "\"not\"",
    "\"null\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"references\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<INT_VALUE>",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "\"\\\'\"",
    "<NON_QUOTE_SPECIAL_CHARACTER>",
    "<NON_QUOTE_CHARACTER>",
  };

}
