/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */
package kr.ac.snu.ids.PRJ1_1_2013_12295;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE = 9;
  /** RegularExpression Id. */
  int TABLE = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int NULL = 12;
  /** RegularExpression Id. */
  int PRIMARY = 13;
  /** RegularExpression Id. */
  int FOREIGN = 14;
  /** RegularExpression Id. */
  int KEY = 15;
  /** RegularExpression Id. */
  int REFERENCES = 16;
  /** RegularExpression Id. */
  int SEMICOLON = 17;
  /** RegularExpression Id. */
  int LEFT_PAREN = 18;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int UNDERSCORE = 21;
  /** RegularExpression Id. */
  int INT_VALUE = 22;
  /** RegularExpression Id. */
  int SIGN = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 25;
  /** RegularExpression Id. */
  int ALPHABET = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create\"",
    "\"table\"",
    "\"not\"",
    "\"null\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"references\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<INT_VALUE>",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
  };

}
