/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */
package kr.ac.snu.ids.PRJ1_3_2013_12295;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int TAB = 2;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int EXIT = 4;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int CHAR = 6;
  /** RegularExpression Id. */
  int DATE = 7;
  /** RegularExpression Id. */
  int CREATE = 8;
  /** RegularExpression Id. */
  int TABLE = 9;
  /** RegularExpression Id. */
  int DROP = 10;
  /** RegularExpression Id. */
  int DESC = 11;
  /** RegularExpression Id. */
  int INSERT = 12;
  /** RegularExpression Id. */
  int INTO = 13;
  /** RegularExpression Id. */
  int DELETE = 14;
  /** RegularExpression Id. */
  int SELECT = 15;
  /** RegularExpression Id. */
  int SHOW = 16;
  /** RegularExpression Id. */
  int TABLES = 17;
  /** RegularExpression Id. */
  int VALUES = 18;
  /** RegularExpression Id. */
  int WHERE = 19;
  /** RegularExpression Id. */
  int PRIMARY = 20;
  /** RegularExpression Id. */
  int FOREIGN = 21;
  /** RegularExpression Id. */
  int KEY = 22;
  /** RegularExpression Id. */
  int REFERENCES = 23;
  /** RegularExpression Id. */
  int NULL = 24;
  /** RegularExpression Id. */
  int NOT = 25;
  /** RegularExpression Id. */
  int OR = 26;
  /** RegularExpression Id. */
  int AS = 27;
  /** RegularExpression Id. */
  int FROM = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int IS = 30;
  /** RegularExpression Id. */
  int ASTERISK = 31;
  /** RegularExpression Id. */
  int END = 32;
  /** RegularExpression Id. */
  int SEMICOLON = 33;
  /** RegularExpression Id. */
  int LEFT_PAREN = 34;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int PERIOD = 37;
  /** RegularExpression Id. */
  int COMP_OP = 38;
  /** RegularExpression Id. */
  int INT_VALUE = 39;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 40;
  /** RegularExpression Id. */
  int DATE_VALUE = 41;
  /** RegularExpression Id. */
  int CHAR_STRING = 42;
  /** RegularExpression Id. */
  int NNNN = 43;
  /** RegularExpression Id. */
  int NN = 44;
  /** RegularExpression Id. */
  int ALPHABET = 45;
  /** RegularExpression Id. */
  int SIGN = 46;
  /** RegularExpression Id. */
  int DIGIT = 47;
  /** RegularExpression Id. */
  int UNDERSCORE = 48;
  /** RegularExpression Id. */
  int QUOTE = 49;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 50;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 51;
  /** RegularExpression Id. */
  int UNEXPECTED = 52;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create\"",
    "\"table\"",
    "\"drop\"",
    "\"desc\"",
    "\"insert\"",
    "\"into\"",
    "\"delete\"",
    "\"select\"",
    "\"show\"",
    "\"tables\"",
    "\"values\"",
    "\"where\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"references\"",
    "\"null\"",
    "\"not\"",
    "\"or\"",
    "\"as\"",
    "\"from\"",
    "\"and\"",
    "\"is\"",
    "\"*\"",
    "<END>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "<COMP_OP>",
    "<INT_VALUE>",
    "<LEGAL_IDENTIFIER>",
    "<DATE_VALUE>",
    "<CHAR_STRING>",
    "<NNNN>",
    "<NN>",
    "<ALPHABET>",
    "<SIGN>",
    "<DIGIT>",
    "\"_\"",
    "\"\\\'\"",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
    "<NON_QUOTE_CHARACTER>",
    "<UNEXPECTED>",
  };

}
